name: Authentication Tutorial

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Matrix paths are independent, and failure for one provider should not
      # halt the running jobs testing another provider.
      fail-fast: false
      # See matrix of secrets...
      # https://sbulav.github.io/terraform/github-actions-matrix-secrets/
      matrix:
        include:
          - client_id: TRANSMUTE_PRODUCTION_CLIENT_ID
            client_secret: TRANSMUTE_PRODUCTION_CLIENT_SECRET
            token_audience: TRANSMUTE_PRODUCTION_TOKEN_AUDIENCE
            token_endpoint: TRANSMUTE_PRODUCTION_TOKEN_ENDPOINT
            api_base_url: TRANSMUTE_PRODUCTION_API_BASE_URL

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run Tests
        env:
          client_id: ${{secrets[matrix.client_id]}}
          client_secret: ${{secrets[matrix.client_secret]}}
          token_audience: ${{secrets[matrix.token_audience]}}
          token_endpoint: ${{secrets[matrix.token_endpoint]}}
          api_base_url: ${{secrets[matrix.api_base_url]}}
        run: |
          npx newman run ./docs/tutorials/authentication/authentication-tutorial.collection.json \
          --env-var CLIENT_ID=$client_id \
          --env-var CLIENT_SECRET=$client_secret \
          --env-var TOKEN_AUDIENCE=$token_audience \
          --env-var TOKEN_ENDPOINT=$token_endpoint \
          --env-var API_BASE_URL=$api_base_url \
          --reporters cli,json
