name: Presentations Exchange

on:
  workflow_call:
  workflow_dispatch:

jobs:
  unit-presentations-exchange:
    name: Presentations Exchange
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "mesur.io-Transmute"
            issuer: MESUR_PRODUCTION
            verifier: TRANSMUTE_STAGING
          - name: "mesur.io-Mavennet"
            issuer: MESUR_PRODUCTION
            verifier: MAVENNET_STAGING
          - name: "Transmute-Mavennet"
            issuer: TRANSMUTE_STAGING
            verifier: MAVENNET_STAGING
          - name: Transmute-"mesur.io"
            issuer: TRANSMUTE_STAGING
            verifier: MESUR_PRODUCTION
          - name: "Mavennet-mesur.io"
            issuer: MAVENNET_STAGING
            verifier: MESUR_PRODUCTION
          - name: "Mavennet-Transmute"
            issuer: MAVENNET_STAGING
            verifier: TRANSMUTE_STAGING
    steps:
      # Check out repo, setup node, and install dependencies.
      # @see https://github.com/actions/setup-node#usage
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - name: Run Tests
        env:
          issuer_organization_did_web: ${{secrets[format('{0}_ORGANIZATION_DID_WEB', matrix.issuer)]}}
          issuer_client_id: ${{secrets[format('{0}_CLIENT_ID', matrix.issuer)]}}
          issuer_client_secret: ${{secrets[format('{0}_CLIENT_SECRET', matrix.issuer)]}}
          issuer_token_audience: ${{secrets[format('{0}_TOKEN_AUDIENCE', matrix.issuer)]}}
          issuer_token_endpoint: ${{secrets[format('{0}_TOKEN_ENDPOINT', matrix.issuer)]}}
          issuer_api_base_url: ${{secrets[format('{0}_API_BASE_URL', matrix.issuer)]}}
          verifier_organization_did_web: ${{secrets[format('{0}_ORGANIZATION_DID_WEB', matrix.verifier)]}}
          verifier_client_id: ${{secrets[format('{0}_CLIENT_ID', matrix.verifier)]}}
          verifier_client_secret: ${{secrets[format('{0}_CLIENT_SECRET', matrix.verifier)]}}
          verifier_token_audience: ${{secrets[format('{0}_TOKEN_AUDIENCE', matrix.verifier)]}}
          verifier_token_endpoint: ${{secrets[format('{0}_TOKEN_ENDPOINT', matrix.verifier)]}}
          verifier_api_base_url: ${{secrets[format('{0}_API_BASE_URL', matrix.verifier)]}}
        run: |
          npx newman run ./docs/tutorials/presentations-exchange/presentations-exchange.postman_collection.json \
          --env-var ISSUER_ORGANIZATION_DID_WEB=$issuer_organization_did_web \
          --env-var ISSUER_CLIENT_ID=$issuer_client_id \
          --env-var ISSUER_CLIENT_SECRET=$issuer_client_secret \
          --env-var ISSUER_TOKEN_AUDIENCE=$issuer_token_audience \
          --env-var ISSUER_TOKEN_ENDPOINT=$issuer_token_endpoint \
          --env-var ISSUER_API_BASE_URL=$issuer_api_base_url \
          --env-var VERIFIER_ORGANIZATION_DID_WEB=$verifier_organization_did_web \
          --env-var VERIFIER_CLIENT_ID=$verifier_client_id \
          --env-var VERIFIER_CLIENT_SECRET=$verifier_client_secret \
          --env-var VERIFIER_TOKEN_AUDIENCE=$verifier_token_audience \
          --env-var VERIFIER_TOKEN_ENDPOINT=$verifier_token_endpoint \
          --env-var VERIFIER_API_BASE_URL=$verifier_api_base_url \
          --reporters cli,html,json \
          --reporter-html-export "newman/${{format('{0}-{1}-{2}.html', github.run_id, github.job, matrix.name)}}" \
          --reporter-json-export "newman/${{format('{0}-{1}-{2}.json', github.run_id, github.job, matrix.name)}}"
      # Sanitize newman output and write all reports to the `./docs/reports`
      # folder for publishing, excluding `index.html`, which will be rebuilt
      # during publishing.
      - name: Sanitize Newman Output
        if: ${{ always() }} # Run even when postman tests fail
        run: |
          npm run report:prepare
          rm -f ./docs/reports/index.html
      - uses: actions/upload-artifact@v3
        if: ${{ always() }} # Run even when postman tests fail
        with:
          name: presentations-exchange
          path: docs/reports/
