name: VC-JWT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Matrix paths are independent, and failure for one provider should not
      # halt the running jobs testing another provider.
      fail-fast: false
      # See matrix of secrets...
      # https://sbulav.github.io/terraform/github-actions-matrix-secrets/
      matrix:
        include:
          - organization_did_web: MAVENNET_STAGING_ORGANIZATION_DID_WEB
            client_id: MAVENNET_STAGING_CLIENT_ID
            client_secret: MAVENNET_STAGING_CLIENT_SECRET
            token_audience: MAVENNET_STAGING_TOKEN_AUDIENCE
            token_endpoint: MAVENNET_STAGING_TOKEN_ENDPOINT
            api_base_url: MAVENNET_STAGING_API_BASE_URL
          - organization_did_web: MESUR_IO_PRODUCTION_ORGANIZATION_DID_WEB
            client_id: MESUR_IO_PRODUCTION_CLIENT_ID
            client_secret: MESUR_IO_PRODUCTION_CLIENT_SECRET
            token_audience: MESUR_IO_PRODUCTION_TOKEN_AUDIENCE
            token_endpoint: MESUR_IO_PRODUCTION_TOKEN_ENDPOINT
            api_base_url: MESUR_IO_PRODUCTION_API_BASE_URL
          - organization_did_web: GS1US_PRODUCTION_ORGANIZATION_DID_WEB
            client_id: GS1US_PRODUCTION_CLIENT_ID
            client_secret: GS1US_PRODUCTION_CLIENT_SECRET
            token_audience: GS1US_PRODUCTION_TOKEN_AUDIENCE
            token_endpoint: GS1US_PRODUCTION_TOKEN_ENDPOINT
            api_base_url: GS1US_PRODUCTION_API_BASE_URL

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1

      - name: Run Tests
        env:
          organization_did_web: ${{secrets[matrix.organization_did_web]}}
          client_id: ${{secrets[matrix.client_id]}}
          client_secret: ${{secrets[matrix.client_secret]}}
          token_audience: ${{secrets[matrix.token_audience]}}
          token_endpoint: ${{secrets[matrix.token_endpoint]}}
          api_base_url: ${{secrets[matrix.api_base_url]}}
        run: |
          npx newman run ./docs/tutorials/vc-jwt/vc-jwt.collection.json \
          --env-var ORGANIZATION_DID_WEB=$organization_did_web \
          --env-var CLIENT_ID=$client_id \
          --env-var CLIENT_SECRET=$client_secret \
          --env-var TOKEN_AUDIENCE=$token_audience \
          --env-var TOKEN_ENDPOINT=$token_endpoint \
          --env-var API_BASE_URL=$api_base_url \
          --reporters cli,json
